# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8c7f1e7a059bc888183b2273b70b4312a859baa4763e746a41d7fa11f2caefe253c40050d7bd8420f8f47bcad7c91b0f8516d708bd727e1914193a4b4c538e6

test:
  secret_key_base: ca7a1b0138f3994fe72a60cef3b0708ea865cbe601acfe3e8aad1e12b427ac9f94af43f6c0c30230c5e4666a0652a81a41e1974dd185acd5011819fd651c606e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
